<?xml version="1.0"?>
<package format="2">
  <name>ros_supervisor</name>
  <version>0.1.0</version>
  <description>ROS1 node supervisor</description>
  <maintainer email="user@example.com">User</maintainer>
  <license>MIT</license>

  <buildtool_depend>catkin</buildtool_depend>

  <depend>rospy</depend>
  <depend>std_msgs</depend>
  <depend>message_generation</depend>
  <depend>message_runtime</depend>

  <export>
  </export>
</package>
